[iOS] 사전 질문 추가 질문 UI 구현 및 기능 구현
softeerbootcamp-2nd/H1-MyCarDeepDive pull request #146
Opened 2023-08-17 08:40 UTC by SHcommit

🚨 **Pull request 전에 확인해야 할 사항( [x] 체크해주세요 )** 

- [x]  반드시 확인할 것! **pull a topic/feature/bugfix branch** 에서 develop branch로 PR요청하는지 확인하세요. master/main에 하시면 안됩니다.

- [x]  커밋 또는 모든 커밋의 메시지 스타일이 요청한 구조와 일치하는지 확인해주세요.

- [x] PR작업에 대한 오른쪽의 라벨을 붙여주세요.

## 📌 [요약]

- 1.4화면 사전 기능 추가 질문 및 기능 구현했습니다.
- slider를 구현했습니다.

## ✨ [작업 내용]

코드 재사용을 충분히 하고 
공통적인 화면이 있었고 중간에 UI만 달라지는 화면이 있었는데, UIView타입으로 레이아웃을 지정하고, 이를 초기화 하는 시점에서 UIView의 구체타입을 할당했습니다. 그리고 QuestionViewSendable protocol을 통해서 UIView에서 이벤트 발생할 때마다 데이터 처리를 QuestionViewSendable protocol의 특정 메서드로 (구체타입에서 선언) UIView에서는 delegate 프로퍼티 사용처럼 사용만 하도록 데이터를 전달했습니다. 여기서 protocol을 두가지로 각각의 구체 UIView에 해당하는 프로토콜로 하는 방법에 대해서는 메서드 사용 시점에 타입이 일치하는지 파악해야하는데, 이와 관련해서 다시 공부해봐야할 것 같습니다.

<img width="400" alt="image" src="https://github.com/softeerbootcamp-2nd/H1-MyCarDeepDive/assets/96910404/6daaf751-5471-4f77-87a6-adc2116c66dc">

## 📸  [스크린샷(선택)]

![ezgif com-gif-maker](https://github.com/softeerbootcamp-2nd/H1-MyCarDeepDive/assets/96910404/e03fa948-aba4-4972-b9b1-0de7518c6e2e)

구현 화면입니다.

<img width="656" alt="image" src="https://github.com/softeerbootcamp-2nd/H1-MyCarDeepDive/assets/96910404/9f20955c-6bf3-44e6-91f3-744ec3458470">

이때 프로토콜은 QuestionViewSendable protocol 입니다.

2023-08-17 08:52 UTC, SHcommit commented
SwiftLint 적용 완료!!

2023-08-17 20:42 UTC, SHcommit commented
태그 stackview -> tag item text글자 길어지는 것 고려해 collectionView로 변경

2023-08-18 02:27 UTC, NamSeok-Bae requested changes

2023-08-18 02:27 UTC, NamSeok-Bae commented on GetYa/GetYa/Presentation/Common/ViewController/BaseViewController.swift
> +
nib init 주의!!

2023-08-18 02:27 UTC, NamSeok-Bae commented on GetYa/GetYa/Util/Extension/Int+.swift
> +    }
기존에 있던걸 계속해서 활용하는게 좋습니다.

2023-08-18 04:59 UTC, SHcommit commented on GetYa/GetYa/Presentation/CharacterSelect/AgeViewController.swift
> +// id를 넘겨주는게 좋을 것 같습니다!! (서버랑 합을 맞춰야겠습니닷)
넵 알겠습니다!!

2023-08-18 05:00 UTC, SHcommit commented on GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/Protocol/CharacterDetailSelectViewModelabe.swift
> +}
그런가요 ...? 알겠습니다!!!! 변경하겠습니다  0_0

2023-08-18 05:04 UTC, SHcommit commented on GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/Protocol/QuestionViewSendable.swift
> +extension QuestionViewSendable {
아 구현체에서 원하는 경우만 따로 함수를 선정해서 구현하기 때문에 기본 값을 지정한 것입니다.

2023-08-18 05:05 UTC, SHcommit commented on GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/View/CharacterDetailQuestionListView.swift
> +}
이를 CheckListStackView에서 준수한다면 CheckListStackView를 사용하는 모든 프로퍼티는 QuestionViewSendable 타입을 준수하게 되는것이고 QuestionViewSendable에서 제시된 메서드를 사용하지 않는 경우도 확장되기 때문에 불필요하다고 생각합니다.

2023-08-18 05:06 UTC, SHcommit commented on GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/ViewController/CharacterDetailSelectViewController.swift
> +            static let height = CGFloat(4).scaledHeight
넵!!

2023-08-18 05:10 UTC, SHcommit commented on GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/ViewController/CharacterDetailSelectViewController.swift
> +    }
함수로 묶어보겠습니다 !!!

2023-08-18 14:33 UTC, SHcommit commented on GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/ViewController/CharacterDetailSelectViewController.swift
> +        let totalStep = viewModel.numberOfSteps
호홓,, 예리하시네요. 급하게 작성하느라 그냥 호출했는데 다시 수정해야겠네요: \

2023-08-18 16:39 UTC, SHcommit commented on GetYa/GetYa/Util/Extension/Int+.swift
> +    }
"만원"이 들어간 Commas computed property 제거하고 기존에 정의된 함수에서 "원" 제거했습니다: )

2023-08-18 16:40 UTC, SHcommit commented on GetYa/GetYa/Presentation/Common/ViewController/BaseViewController.swift
> +
수정 완료!!

2023-08-18 16:45 UTC, SHcommit commented on GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/ViewController/CharacterDetailSelectViewController.swift
> +        let totalStep = viewModel.numberOfSteps
리빌딩 완료 : )

2023-08-18 16:46 UTC, SHcommit commented on GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/ViewController/CharacterDetailSelectViewController.swift
> +    override func didTapNavigationBackButton() {
리뷰 반영했습니다 : ]

2023-08-18 22:14 UTC, NamSeok-Bae commented on GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/Protocol/QuestionViewSendable.swift
> +extension QuestionViewSendable {
저희 Question 특정상 디폴값이 가지고 있기떄문에 0으로 초기화하는게 좋을거같습니다!

그리고 프로토콜을 나눈다면 Question Stackview의 Question Number 을 보내줄 프로토콜, Slider의 값을 보내줄 프로토콜
2개를 SRP 하게 나눠서 각 뷰에 지정해주는건 어떨까요?

2023-08-18 22:23 UTC, NamSeok-Bae approved these changes

2023-08-18 22:32 UTC, NamSeok-Bae commented on GetYa/GetYa/Presentation/CharacterSelect/CharacterDetailSelect/ViewModel/CharacterDetailSelectViewModel.swift
> +}
ViewModel 이라는 이름이 혼동을 가져오는 것 같습니다. 각 뷰의 데이터를 담는 모델이긴하지만 값만을 가지고 있기때문에 이것은 자체적인 이름 가져야한다고 생각합니다.
struct MySlider {
    var minimumCarPrice: Int
    var maximumCarPrice: Int
}
와 같이, 저번에 얘기했던거처럼 저희가 사용할 데이터를 보관할 데이터 객체를 만들면 좋겠다는 생각이 드는군요!

2023-08-18 22:32 UTC, NamSeok-Bae approved these changes

2023-08-18 22:32 UTC, NamSeok-Bae commented
고생하셨습니다!! 코멘트 2개를 달았는데, 이것은 치명적인게 아니니 나중에 다시 고민해보죠!

2023-08-19 04:12 UTC, merged